=== Hunt-Gather-Create/airbyte-connectors/sources/buildkite-source/resources/schemas/builds.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": true,
    "properties": {
        "uuid": {
            "type": "string"
        },
        "message": {
            "type": "string"
        },
        "number": {
            "type": "number"
        },
        "createdAt": {
            "type": "string"
        },
        "startedAt": {
            "type": ["string","null"]
        },
        "finishedAt": {
            "type": ["string","null"]
        },
        "state": {
            "type": "string"
        },
        "url": {
            "type": "string"
        },
        "commit": {
            "type": "string"
        },
        "jobs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "type": "string"
                    },
                    "uuid": {
                        "type": "string"
                    },
                    "label": {
                        "type": ["string","null"]
                    }, 
                    "createdAt": {
                        "type":["string","null"]
                    },
                    "startedAt": {
                        "type": ["string","null"]
                    },
                    "finishedAt": {
                        "type": ["string","null"]
                    },
                    "triggered": {
                        "type": [
                            "object",
                            "null"
                        ],
                        "additionalProperties": true,
                        "properties": {
                            "createdAt": {
                                "type":["string","null"]
                            },
                            "startedAt": {
                                "type": ["string","null"]
                            },
                            "finishedAt": {
                                "type": ["string","null"]
                            }
                        }
                    },
                    "unblockedAt": {
                        "type": "string"
                    },
                    "url": {
                        "type":  ["string","null"]
                    },
                    "command": {
                        "type": "string"
                    }
                }
              }
        },
        "pipeline": {
            "type": "object",
            "properties": {
                "slug": {
                    "type": "string"
                },
                "repository": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string"
                        },
                        "provider": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "organization": {
                    "type": "object",
                    "properties": {
                        "slug": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== Hunt-Gather-Create/airbyte-connectors/sources/buildkite-source/test_files/builds.json
[
    {
        "uuid": "4c55126e-0f8e-4d48-9ce2-7071fecb70cd",
        "message": "test 1",
        "number": 2,
        "createdAt": "2021-12-20T03:37:40.894Z",
        "startedAt": null,
        "finishedAt": null,
        "state": "SCHEDULED",
        "url": "https://buildkite.com/devcube/kelvin-test/builds/2",
        "commit": "HEAD",
        "jobs": [
            {
                "uuid": "443f71ef-e264-4051-a062-e6f2b4e91170",
                "label": "",
                "state": "SCHEDULED",
                "createdAt": "2021-12-20T03:37:40.885Z",
                "finishedAt": null,
                "startedAt": null,
                "url": "https://buildkite.com/devcube/kelvin-test/builds/2#443f71ef-e264-4051-a062-e6f2b4e91170",
                "command": ""
            }
        ]
    },
    {
        "uuid": "ee00ecd6-8d97-426d-9f0f-1a618b8f5023",
        "message": "Test build",
        "number": 1,
        "createdAt": "2021-12-20T03:28:25.066Z",
        "startedAt": null,
        "finishedAt": null,
        "state": "SCHEDULED",
        "url": "https://buildkite.com/devcube/kelvin-test/builds/1",
        "commit": "HEAD",
        "jobs": [
            {
                "uuid": "109382d0-4ef0-498c-8d56-cd58478b464e",
                "label": "",
                "state": "SCHEDULED",
                "createdAt": "2021-12-20T03:28:25.054Z",
                "finishedAt": null,
                "startedAt": null,
                "url": "https://buildkite.com/devcube/kelvin-test/builds/1#109382d0-4ef0-498c-8d56-cd58478b464e",
                "command": ""
            }
        ]
    }
]
